// apply-content.js — DO NOT EDIT THIS FILE
// Reads values from js/content.js and injects them into the page.
// To change text, edit js/content.js instead.
(function () {
  function getVal(obj, path) {
    return path.split('.').reduce(function (acc, key) {
      return acc != null ? acc[key] : undefined;
    }, obj);
  }

  function applyContent() {
    if (typeof COPY === 'undefined') return;
    document.querySelectorAll('[data-c]').forEach(function (el) {
      var val = getVal(COPY, el.getAttribute('data-c'));
      if (val === undefined || val === null) return;
      if (el.hasAttribute('data-c-html')) {
        el.innerHTML = val;
      } else {
        el.textContent = val;
      }
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', applyContent);
  } else {
    applyContent();
  }
})();
